In [2]:
#list: different datatypes
#arry: similar datatypes, less memory, fast and convinient
import numpy as np

In [8]:
a = np.array([1,2,3,4])#1d
a

array([1, 2, 3, 4])

In [9]:
np.array([[1,2], [3,4]])#2d

array([[1, 2],
       [3, 4]])

In [10]:
np.array([1,2,3], dtype ="complex")


array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
np.array((1,2,3)) #using tuple

array([1, 2, 3])

In [13]:
#arange(): create array of evenly spaced values
#zeros(): create array filled with zeros
np.arange(1,10,2, dtype="float")

array([1., 3., 5., 7., 9.])

In [17]:
#eye(): returns array filled with zeros except in the k-th diagonal, whose values are equal to 1##
#help(np.eye)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
#identity():Return a identity matrix i.e. a square matrix with ones on the main daignol
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#ndim():no. of dimensions
#shape(): in 1d number of elements in the array, 2d:nu.of rows and cols,  3d:dimensions
c=np.zeros((2,3,4))# 2array, 3rows,4cols
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
c.shape

(2, 3, 4)

In [25]:
#size:total no. of elements present in arry(in above eg: it multiplies all2*3*4)
c.size

24

# datatype

In [26]:
#dtype: to know abt data types and zeros default has float dtype
#itemsize(): size ofthe each item of array in byts. 1bytes=8bits
#eg: float64: 64/8= 8byte each item take 8bytes
#eg: int32: 32/8 = 4bytes
c.itemsize

8

In [28]:
#1, datatype can be used as fun.2, can be refered by character code, 3change dtye using .astype()

d=np.zeros(5)
d.dtype  #by default it has float64

dtype('float64')

In [31]:
#in numpy int refer to np.int_, bool=np.bool, float= np.float, complex=np.complex
b=np.zeros(6, dtype=np.int8) # if we write directly dtype=int8 it shows error bcoz int8 belongs to numpy so we should mension
b

array([0, 0, 0, 0, 0, 0], dtype=int8)

In [32]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [33]:
a.astype(int) #np.float64(a) this is another way to convert data types, here we use datatype as function directly

array([0, 0, 0])

# indexing

In [37]:
e=np.array([[1,2],[3,4]]) #in 2d can also use -ve
e[0][1]

2

In [41]:
c[0][1][2]   #1. from which array (0-1st array, (1-2nd array)), 2. row index, 3. col index we can also use -ve index

0.0

In [45]:
#slicing:2d:[start:end:step, start:end:step]
e[1:, 1:]

array([[4]])

In [49]:
f= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,0]])
f[1:,1:]

array([[ 6,  7,  8],
       [10, 11,  0]])

In [48]:
f[::,::2] #step 2

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [50]:
#3d: [start:end:step, start:end:step, start:end: step] 
#advanced index: 2types, 1, integer index, 2, boolean index
g=np.arange(1,10)  # if i want to get 2,5,6 elements
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
index= np.array([1,4, 5]) #here we are creating array of index or we can also give directly g[[1,4,5]
g[index]                   # use index array as index

In [53]:
h= np.array([[1,2,3],[4,5,6],[7,9,8]]) # if i want to get 3, 7
h[[0,2],[2,0]]                         #row, col

array([3, 7])

In [61]:
j= np.array([[1,-2,3],[4,-2,3]])
j

array([[ 1, -2,  3],
       [ 4, -2,  3]])

In [63]:
j[j<0]*2   #boolean indexing we can also perform operations

array([-4, -4])

In [ ]:
#broadcasting rules:1, size of each dimension should be same, 2. size of one of the dimension should be 1.
#if the dimensions is not same the add 1 to the left side of the dime. or check both are wqual

# manipulation

In [ ]:
#reshape: it gives new shape to array withount changing the data syntax:numpy.reshape(array,shape, order)
#here order is C(row wise)/A(fortan like )/F(column wise operation), default is "C", return new array
#resize: it can change the data of an array and gives new shape syntax: numpy. resize(array, shape)

In [3]:
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
i.shape

(10,)

In [9]:
k = np.reshape(i,(5,2))# row wise peration, we can also write like i.reshape((5,2))
k

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
k.shape

(5, 2)

In [11]:
l=np.reshape(i,(5,2), order="F")#col wise operation
l

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [13]:
np.resize(i,(5,3)) # it resize the new array, if write like i.resize((5,3)) it change tha original array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 1],
       [2, 3, 4]])

In [ ]:
#flatten(): it gives copy of the arry collabes in to 1D and convert 2D or 3D to 1D
#syntax: ndarray.flatten(order= "c/A/F/K"), it is a method od the ndarray
#ravel():same as flattten but it will copy the element inly when it is needed else it will give view of the rray
#syntax: numpy.ravel(a, order="c"), it is library level function

In [14]:
df = np.array([[1,2],[3,4]])
df

array([[1, 2],
       [3, 4]])

In [18]:
df.flatten(order="F")

array([1, 3, 2, 4])

In [19]:
df.ravel()

array([1, 2, 3, 4])

In [ ]:
#transposse:it rearrange the given array, sy: numpy. transpose(array, axis= none), axis=(1,0)/(0,1) default none
#(1,0) : reverse order, (0,1): same as i/p, in this we can do change all axises
#swapaxes():it is used to inter change any two axis of given array, syntax: numpy.swapaxes(array, axis1, axis2)

In [21]:
df1= np.arange(1,11).reshape(5,2)
df1    #df1.transpose() we can also write like this when we dont want the axis


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
np.transpose(df1) #default axis = none (1,0)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [24]:
df2= np.arange(1,25).reshape(2,3,4) # if i want to get 3: 2d array, 4:rows, 2:columns
df2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [26]:
np.transpose(df2,(1,2,0)) # here axis 0: 2, axis1 : 3, axis 2: 4....... etc.,

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [28]:
np.swapaxes(df,0,1) #2d

array([[1, 3],
       [2, 4]])

In [29]:
df3 = np.array([[1,2,3]])
df3

array([[1, 2, 3]])

In [32]:
df3.shape


(1, 3)

In [31]:
np.swapaxes(df3,1,0)

array([[1],
       [2],
       [3]])

In [33]:
np.swapaxes(df2,1,2)  # row axis i 1, col: 2

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [37]:
# concatinate():used to concatinate along the existing axis
#syntax: numpy.concatenate(array, axis=0, out= none), we cant join diff. dimensions
#vstack: used to join vertically syn: numpy.vstack(tuple), 1d: shape-2d, 2d: axis=0
#hstack: usedto join horizontally 1d: shape-1d, 2d: axis=1

#split(): used to spli the array syntax: numpy.split(arrray, section, axis=0)
#note: be carefu; aby the section parameter if we cant divide array based on section value equally it will give error.
#hspli(): axis=1
#vsplit(): axis=0

In [34]:
z= np.arange(1,5)
x= np.arange(6)
np.concatenate((z,x))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [35]:
c= np.zeros(10)
np.concatenate((z,x), out=c) # out used to  where to store the values

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])

In [36]:
c

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])